#!/bin/bash
#PBS -N "info1"
#PBS -l walltime=20:00:00
#PBS -l nodes=1:ppn=8
#PBS -j oe
#PBS -l mem=4GB

python3 /fs/project/PHS0293/cancerproj/cimp-noncimp/randomforest/evalRandforst.py "/fs/project/PHS0293/cancerproj/cimp-noncimp/featurefilter/filtered_infogain1.csv" > /fs/project/PHS0293/cancerproj/cimp-noncimp/randomforest/info1_results.txt
